---
- name: Install docker
  hosts: all
  become: yes
  tasks:
    - name: add docker apt key
      apt_key: >
        id=58118E89F3A912897C070ADBF76221572C52609D
        keyserver=hkp://p80.pool.sks-keyservers.net:80
        state=present

    - name: add docker apt repository
      apt_repository: >
        repo="deb https://apt.dockerproject.org/repo ubuntu-trusty main"
        state=present
        update_cache=yes

    - name: install docker and requirements
      apt: >
        pkg={{item}}
        state=present
      with_items:
        - apparmor
        - docker-engine

    - name: configure docker
      copy: content='DOCKER_OPTS=""'
        dest=/etc/default/docker
      notify: restart docker

    - name: allow vagrant user to run docker commands without sudo
      user: name=vagrant append=yes groups=docker

    - name: install required python packages for ansible and docker
      apt: pkg={{item}} state=latest
      with_items: [python-pip, python-dev]

    # As of ansible v1.9.1, the docker module uses an older version of the docker-py python package.
    # https://github.com/ansible/ansible-modules-core/issues/1227
    - name: install the version of docker-py used by ansible
      pip: 
         name: docker-py
         version: 1.7.0

  handlers:
    # I can't use the service module because of an issue with ansible and upstart :(
    # https://github.com/ansible/ansible-modules-core/issues/1170
    - name: restart docker
      command: service docker restart

- name: Create docker image and run
  hosts: all
  become: yes  
  tasks:
    - name: upload the site directory to the docker host
      synchronize: src=site dest=/tmp

    - name: build the image
      command: docker build -t built-by-ansible:ex2 /tmp/site

    - name: run the site in a docker container
      docker_container:
        name: site2
        image: "built-by-ansible:ex2"
        state: started
        restart: yes
        published_ports: 8080:80
